# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to AWS

on:
  pull_request:
    branches: [ qa ]

jobs:
  deploy:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2

    - name: Npm Install && build
      run: |
        npm install
        npm run build:${{ github.event.pull_request.base.ref }}

    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
       args: --acl public-read --delete
      env:
       AWS_S3_BUCKET: ${{ secrets.QA_AWS_S3_BUCKET }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: 'ca-central-1'
       SOURCE_DIR: 'build'

    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@v1.3
      env:
       DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
       PATHS: '/*'
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: 'ca-central-1'
