name: "Make a release"
on:
  pull_request:
    branches: [qa, production]
    types: [closed]
jobs:
  build-ui:
    name: "Build the code for SalusConnect website"
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up the environment variable for Release Version
        run: |
          echo "RELEASE_VERSION=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Set up the environment variable for Release Tag Name
        run: |
          echo "TAG_NAME=${{ github.event.pull_request.base.ref }}-${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV

      - name: Set up the environment variable for Assets filename
        run: |
          echo "ASSETS_FILE_NAME=${{ env.TAG_NAME }}.zip" >> $GITHUB_ENV

      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Install npm dependencies"
        run: npm install

      - name: "Build the website"
        run: npm run build-${{ github.event.pull_request.base.ref }}

      - name: "Archive site content"
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ env.ASSETS_FILE_NAME }}
          path: dist/simply-doc/
          directory: .

      - name: "Create Github release"
        id: "create-new-release"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.TAG_NAME}}
          release_name: Release v.${{ env.TAG_NAME }}

      - name: "Upload asset to Github Release"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url}}
          asset_path: ./${{ env.ASSETS_FILE_NAME }}
          asset_name: ${{ env.ASSETS_FILE_NAME }}
          asset_content_type: application/zip
